import React from 'react'
import { Link } from 'react-router-dom'
import "../styles/pages/home.css"
const Home = () => {

  return (
    <div className='container my-5' id='home-section'>

      <Link to="/products">Click to view all products</Link>
      <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Id cumque temporibus inventore laboriosam aspernatur, soluta corporis? Eum hic dignissimos rem distinctio libero labore atque doloremque ratione ipsum iusto obcaecati nulla quia pariatur repudiandae expedita vel nostrum quo mollitia, assumenda delectus numquam consectetur impedit nihil! Possimus, impedit deserunt? Sapiente magnam, facere enim rerum repellat expedita esse eius? Laborum corporis quaerat quia vero commodi labore distinctio enim maiores at sapiente expedita illum ipsa inventore maxime facilis cum magnam neque est eos unde eveniet, molestias possimus doloribus. Fuga saepe quam sed aspernatur laborum quibusdam, voluptatum non soluta, excepturi, a praesentium nemo quidem id! Saepe consectetur possimus, laboriosam voluptatem excepturi placeat vel aliquid libero quaerat, veniam suscipit iusto rem doloremque tempora quasi repellendus exercitationem itaque! Recusandae est placeat quod aspernatur harum. Tempore aspernatur blanditiis reprehenderit nemo autem nam sint quibusdam commodi non delectus facilis obcaecati, eveniet deleniti aliquid ratione qui mollitia? Consequuntur explicabo doloremque, beatae architecto dolore aliquid fuga illum porro minima iste, molestias dolores est modi quaerat corporis, atque fugiat dolorum. Maiores eligendi, ipsa aspernatur atque, nam, corporis optio rem facilis eum provident earum in voluptatum. Laudantium, ullam placeat? Expedita mollitia odit alias veritatis in a rem doloribus error eveniet consequuntur est repellendus veniam fugit, natus voluptas dicta tempora dolor neque cum cumque magnam beatae amet! Dolorem aspernatur minus ipsam expedita illum impedit nulla asperiores debitis esse sequi quae minima eius repudiandae ab officia, est voluptas error delectus? Similique consequatur illum voluptatibus neque. Dolorem fugiat amet debitis nam aperiam tempore eligendi asperiores veritatis vero similique quasi ipsam praesentium perspiciatis necessitatibus ex, explicabo officiis consequatur ipsa cupiditate. Eligendi, maiores autem cumque itaque voluptas nesciunt minima exercitationem quasi quaerat minus modi quia assumenda sed consectetur nam fugiat dicta nisi officiis voluptates nostrum. Impedit nihil ea officia tempora. Nostrum dolor in corrupti exercitationem sed illum harum?</p>
      <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Id cumque temporibus inventore laboriosam aspernatur, soluta corporis? Eum hic dignissimos rem distinctio libero labore atque doloremque ratione ipsum iusto obcaecati nulla quia pariatur repudiandae expedita vel nostrum quo mollitia, assumenda delectus numquam consectetur impedit nihil! Possimus, impedit deserunt? Sapiente magnam, facere enim rerum repellat expedita esse eius? Laborum corporis quaerat quia vero commodi labore distinctio enim maiores at sapiente expedita illum ipsa inventore maxime facilis cum magnam neque est eos unde eveniet, molestias possimus doloribus. Fuga saepe quam sed aspernatur laborum quibusdam, voluptatum non soluta, excepturi, a praesentium nemo quidem id! Saepe consectetur possimus, laboriosam voluptatem excepturi placeat vel aliquid libero quaerat, veniam suscipit iusto rem doloremque tempora quasi repellendus exercitationem itaque! Recusandae est placeat quod aspernatur harum. Tempore aspernatur blanditiis reprehenderit nemo autem nam sint quibusdam commodi non delectus facilis obcaecati, eveniet deleniti aliquid ratione qui mollitia? Consequuntur explicabo doloremque, beatae architecto dolore aliquid fuga illum porro minima iste, molestias dolores est modi quaerat corporis, atque fugiat dolorum. Maiores eligendi, ipsa aspernatur atque, nam, corporis optio rem facilis eum provident earum in voluptatum. Laudantium, ullam placeat? Expedita mollitia odit alias veritatis in a rem doloribus error eveniet consequuntur est repellendus veniam fugit, natus voluptas dicta tempora dolor neque cum cumque magnam beatae amet! Dolorem aspernatur minus ipsam expedita illum impedit nulla asperiores debitis esse sequi quae minima eius repudiandae ab officia, est voluptas error delectus? Similique consequatur illum voluptatibus neque. Dolorem fugiat amet debitis nam aperiam tempore eligendi asperiores veritatis vero similique quasi ipsam praesentium perspiciatis necessitatibus ex, explicabo officiis consequatur ipsa cupiditate. Eligendi, maiores autem cumque itaque voluptas nesciunt minima exercitationem quasi quaerat minus modi quia assumenda sed consectetur nam fugiat dicta nisi officiis voluptates nostrum. Impedit nihil ea officia tempora. Nostrum dolor in corrupti exercitationem sed illum harum?</p>
      <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Id cumque temporibus inventore laboriosam aspernatur, soluta corporis? Eum hic dignissimos rem distinctio libero labore atque doloremque ratione ipsum iusto obcaecati nulla quia pariatur repudiandae expedita vel nostrum quo mollitia, assumenda delectus numquam consectetur impedit nihil! Possimus, impedit deserunt? Sapiente magnam, facere enim rerum repellat expedita esse eius? Laborum corporis quaerat quia vero commodi labore distinctio enim maiores at sapiente expedita illum ipsa inventore maxime facilis cum magnam neque est eos unde eveniet, molestias possimus doloribus. Fuga saepe quam sed aspernatur laborum quibusdam, voluptatum non soluta, excepturi, a praesentium nemo quidem id! Saepe consectetur possimus, laboriosam voluptatem excepturi placeat vel aliquid libero quaerat, veniam suscipit iusto rem doloremque tempora quasi repellendus exercitationem itaque! Recusandae est placeat quod aspernatur harum. Tempore aspernatur blanditiis reprehenderit nemo autem nam sint quibusdam commodi non delectus facilis obcaecati, eveniet deleniti aliquid ratione qui mollitia? Consequuntur explicabo doloremque, beatae architecto dolore aliquid fuga illum porro minima iste, molestias dolores est modi quaerat corporis, atque fugiat dolorum. Maiores eligendi, ipsa aspernatur atque, nam, corporis optio rem facilis eum provident earum in voluptatum. Laudantium, ullam placeat? Expedita mollitia odit alias veritatis in a rem doloribus error eveniet consequuntur est repellendus veniam fugit, natus voluptas dicta tempora dolor neque cum cumque magnam beatae amet! Dolorem aspernatur minus ipsam expedita illum impedit nulla asperiores debitis esse sequi quae minima eius repudiandae ab officia, est voluptas error delectus? Similique consequatur illum voluptatibus neque. Dolorem fugiat amet debitis nam aperiam tempore eligendi asperiores veritatis vero similique quasi ipsam praesentium perspiciatis necessitatibus ex, explicabo officiis consequatur ipsa cupiditate. Eligendi, maiores autem cumque itaque voluptas nesciunt minima exercitationem quasi quaerat minus modi quia assumenda sed consectetur nam fugiat dicta nisi officiis voluptates nostrum. Impedit nihil ea officia tempora. Nostrum dolor in corrupti exercitationem sed illum harum?</p>
    </div>
  )
}

export default Home
